import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { signOut, auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="flex items-center justify-between p-4 shadow">
          <h1 className="text-xl font-bold">
            <Link href="/">📚 Libaray App</Link>
          </h1>
          {session?.user ? (
            <form
              action={async () => {
                "use server";
                await signOut({ redirectTo: "/" });
              }}
            >
              <Button type="submit">ログアウト</Button>
            </form>
          ) : (
            <Button variant="outline" asChild>
              <Link className="" href="/login">
                ログイン
              </Link>
            </Button>
          )}
        </header>
        <main className="flex-1 px-2 w-full max-w-2xl mx-auto">{children}</main>
        <footer className="text-center text-sm text-muted-foreground py-6 border-t">
          © 2025 LibraryApp. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
